### ISSUE TITLE
js$obj.getwidestring doesn't work

### ISSUE THREAD

**Issue by aschegolskiy** [mnf71/udr-lkJSON#3]
With win-1251 charset (database and connection) code below returns empty strings.

execute block returns (res varchar(1024))
as
  declare variable jso ty$pointer;
begin
  jso = js$func.parsestring('{"str1":"str_val1"}');
  res = js$obj.getwidestring(jso,0); suspend;
  res = js$obj.getwidestringbyname(jso,'str1'); suspend;
  js$Obj.dispose(jso);
end

**Comment by mnf71** [comment]
Uhhh! Fixed, thanks.

**Comment by mnf71** [comment]
Closed
